quotes = ["To be, or not to be", 
"My kingdom for a horse", 
"Get thee to a nunnery", 
"There are more things in heaven and earth", 
"Brave new world", 
"The dogs of war", 
"Let's kill all the lawyers", 
"To thine ownself be true", 
"Once more unto the breach", 
"Good night sweet prince", 
"I will wear my heart upon my sleeve", 
"When beggars die, there are no comets seen", 
"Lord, what fools these mortals be", 
"Uneasy lies the head that wears a crown", 
"Sweets to the sweet", 
"What's past is prologue", 
"It was greek to me", 
"Motley fool", 
"Et tu, Brute", 
"Sound and fury", 
"Friends, romans, countrymen", 
"Something wicked this way comes", 
"To sleep: perchance to dream", 
"Green-eyed monster", 
"This was the noblest Roman of them all", 
"Oft expectation fails and most oft there Where most it promises", 
"Eye of newt and toe of frog", 
"Frailty, thy name is woman", 
"What light through yonder window breaks", 
"That this too too solid flesh would melt", 
"When we have shuffled off this mortal coil", 
"Trippingly on the tongue", 
"That I were a glove upon that hand", 
"Hoist with his own petard", 
"Dog will have his day", 
"Think you I am no stronger than my sex", 
"Cowards die many times before their deaths", 
"How poor are they that have not patience", 
"Bell, book, and candle", 
"Something is rotten in the state of Denmark", 
"Beware the ides of March", 
"Quality of mercy", 
"A stage where every man must play a part", 
"My words fly up, my thoughts remain below", 
"Though this be madness, yet there is method in 't", 
"Is this a dagger which I see before me", 
"Now go we in content To liberty and not to banishment", 
"Band of brothers", 
"Alas, poor Yorick! I knew him", 
"The world's mine oyster", 
"Nothing will come of nothing", 
"That man that hath a tongue", 
"All the world's a stage", 
"The course of true love never did run smooth", 
"Love looks not with the eyes, but with the mind", 
"Let every eye negotiate for itself", 
"Brevity is the soul of wit", 
"What the dickens", 
"The evil that men do lives after them", 
"Salad days", 
"Sleep that knits up the ravell'd sleeve of care", 
"Who steals my purse steals trash", 
"Kiss me, Kate", 
"The play 's the thing", 
"I am constant as the northern star", 
"The man that hath no music in himself", 
"We are such stuff As dreams are made on", 
"This was the most unkindest cut of all", 
"Journeys end in lovers meeting", 
"Yond Cassius has a lean and hungry look", 
"My only love sprung from my only hate", 
"I am fortune's fool", 
"Loved not wisely but too well", 
"O coward conscience, how dost thou afflict me", 
"When shall we three meet again", 
"A plague o' both your houses", 
"Out, damned spot", 
"To-morrow, and to-morrow, and to-morrow", 
"Our remedies oft in ourselves do lie", 
"Not that I loved Caesar less", 
"Winter of our discontent", 
"Parting is such sweet sorrow", 
"O Romeo, Romeo! wherefore art thou Romeo", 
"The lady protests too much, methinks", 
"What a piece of work is a man", 
"The fault, dear Brutus, is not in our stars", 
"All that glitters is not gold", 
"What's in a name", 
"Thus with a kiss I die", 
"Slings and arrows of outrageous fortune", 
"Neither a borrower nor a lender be", 
"This blessed plot, this earth, this realm, this england", 
"In my mind's eye", 
"Too much of a good thing", 
"We have seen better days", 
"For ever and a day", 
"Off with his head!", 
"It is the east, and Juliet is the sun", 
"For you and I are past our dancing days", 
"Love is blind", 
"If you prick us, do we not bleed?", 
"The short and the long of it", 
"As good luck would have it", 
"He will give the devil his due", 
"The better part of valour is discretion", 
"Eaten me out of house and home", 
"Worm will turn", 
"Having nothing, nothing can he lose", 
"A dish fit for the gods", 
"Brutus is an honourable man", 
"What's done is done", 
"Fair is foul, and foul is fair", 
"Charmed life", 
"Milk of human kindness", 
"Double, double toil and trouble", 
"Out, out, brief candle!", 
"Tale told by an idiot", 
"Men of few words", 
"The jaws of death", 
"Fool's paradise", 
"Foregone conclusion", 
"Tower of strength", 
"There's the rub", 
"Bag and baggage", 
"Bated breath", 
"Cold comfort", 
"Come full circle", 
"Dead as a doornail", 
"Every inch a king", 
"Good riddance", 
"Hold a candle to", 
"Household words", 
"Have not slept one wink", 
"Greatness thrust upon them", 
"Into thin air", 
"Laughing-stock", 
"Own flesh and blood", 
"One fell swoop", 
"Play fast and loose", 
"Pomp and circumstance", 
"Shooting star", 
"Skim milk", 
"Short shrift", 
"Something in the wind", 
"Sorry sight", 
"Throw cold water", 
"To the manner born", 
"The short and the long", 
"What is not holy, that we swear not by", 
"Wild-goose chase", 
"A dateless bargain to engrossing death", 
"With mirth and laughter let old wrinkles come", 
"Such as we are made of, such we be", 
"Words pay no debts", 
"We know what we are", 
"The devil can cite Scripture for his purpose", 
"Love sought is good, but given unsought better", 
"The miserable have no other medicine but only hope", 
"God has given you one face", 
"Our doubts are traitors", 
"Modest doubt is call'd the beacon of the wise", 
"He that dies pays all debts", 
"Nothing in his life became him like the leaving it", 
"A man can die but once", 
"Watchman to my heart", 
"Sweet are the uses of adversity", 
"If music be the food of love, play on", 
"There is a history in all men's lives", 
"Men at some time are masters of their fates", 
"There's small choice in rotten apples", 
"Souls gives light in darkness", 
"My bounty is as boundless as the sea", 
"There is no darkness but ignorance", 
"Through tatter'd clothes small vices do appear", 
"The glass of fashion", 
"Have more than thou showest", 
"In time we hate that which we often fear", 
"It is a wise father that knows his own child", 
"Let's mock the midnight bell", 
"I have lived long enough", 
"We that are true lovers run into strange capers", 
"The will is infinite and the execution confined", 
"Few love to hear the sins they love to act", 
"One may smile, and smile, and be a villain", 
"The abuse of greatness", 
"Vale of years", 
"Good counsellors lack no clients", 
"When I waked, I cried to dream again", 
"The empty vessel makes the greatest sound", 
"Our bodies are our gardens", 
"Age cannot wither her", 
"Tis the mind that makes the body rich", 
"Flies to wanton boys", 
"The undiscover'd country", 
"My crown is in my heart", 
"Make not your thoughts your prisons", 
"Striving to better, oft we mar what's well", 
"Defer no time, delays have dangerous ends", 
"Better three hours too soon than a minute too late", 
"I do desire we may be better strangers", 
"My library was dukedom large enough", 
"Suspicion always haunts the guilty mind", 
"Patch grief with proverbs", 
"Friendship is constant in all other things", 
"I will praise any man that will praise me", 
"Fashion wears out more apparel than the man", 
"The tartness of his face sours ripe grapes", 
"Oftentimes excusing of a fault doth make the fault the worse by the excuse", 
"Substance of the ambitious", 
"Action is eloquence", 
"Thought is free", 
"Life is as tedious as a twice-told tale", 
"Give every man thy ear, but few thy voice", 
"Reason and love keep little company together", 
"We wound our modesty", 
"Nature must obey necessity", 
"I am a kind of burr", 
"Get thee glass eyes", 
"In delay there lies no plenty", 
"They stumble that run fast", 
"Men must endure", 
"He that hath a beard", 
"Your tale, sir, would cure deafness", 
"Let us call thee devil", 
"My age is as a lusty winter", 
"He's winding up the watch of his wit", 
"A little brief authority", 
"Tell truth and shame the devil", 
"Whirligig of time", 
"Left me naked to mine enemies", 
"I said I would die a bachelor", 
"Strange bed-fellows", 
"We were not born to sue", 
"How apt the poor are to be proud", 
"Bow, stubborn knees", 
"Strong reasons make strong actions", 
"Heat not a furnace for your foe", 
"Some rise by sin, and some by virtue fall", 
"I had rather be a toad", 
"No legacy is so rich as honesty", 
"Look into happiness through another man's eyes", 
"Rich gifts wax poor when givers prove unkind", 
"Tide in the affairs of men", 
"Death makes no conquest of this conqueror", 
"When workmen strive to do better than well", 
"Conceit, more rich in matter than in words, brags of his substance", 
"Sharper than a serpent's tooth", 
"Great stage of fools", 
"Had I but followed the arts", 
"Ambition should be made of sterner stuff", 
"Lord, Lord, how subject we old men are to this vice of lying", 
"My soul is in the sky", 
"We waste our lights in vain, like lamps by day", 
"So wise so young", 
"You take my life when you do take the means whereby I live", 
"Call back yesterday", 
"Thou art swift to enter in the thoughts of desperate men", 
"Simply the thing I am shall make me live", 
"When love begins to sicken and decay", 
"Men have died from time to time", 
"Manhood is melted into courtesies", 
"Report me and my cause aright", 
"Every good servant does not all commands", 
"Thou seest I have more flesh than another man", 
"Patience be a tired mare", 
"A still and quiet conscience", 
"Great men that have flattered the people", 
"I durst not laugh, for fear of opening my lips and receiving the bad air", 
"Show me the steep and thorny way to heaven", 
"I have bought golden opinions from all sorts of people", 
"Purpose is but the slave to memory", 
"Reputation, reputation, reputation", 
"A giant's strength", 
"Loves to hear himself talk", 
"I do not much dislike the matter", 
"When a gentleman is disposed to swear", 
"When the age is in, the wit is out", 
"He jests at scars that never felt a wound", 
"Touch of nature", 
"Like a strange soul", 
"Tis mad idolatry to make the service greater than the god", 
"We'll teach you to drink deep ere you depart", 
"Why should honour outlive honesty", 
"Though I am not naturally honest", 
"What stronger breastplate than a heart untainted", 
"Have an itching palm", 
"He receives comfort like cold porridge", 
"I have touch'd the highest point of all my greatness", 
"A friend should bear his friend's infirmities", 
"There's a special providence in the fall of a sparrow", 
"I can express no kinder sign of love than this kind kiss", 
"He uses his folly like a stalking-horse", 
"Of all base passions, fear is most accursed", 
"Sweet aspect of princes", 
"Wallet at his back", 
"Glory is like a circle in the water", 
"She excels each mortal thing upon the dull earth dwelling", 
"Many can brook the weather that love not the wind", 
"Now, neighbour confines, purge you of your scum", 
"Send danger from the east unto the west", 
"The time is out of joint", 
"I have full cause of weeping", 
"I dare do all that may become a man", 
"A valiant flea", 
"Screw your courage to the sticking-place", 
"God has given you one face, and you make yourselves another", 
"When rich villains have need of poor ones", 
"Now join your hands", 
"Tis an ill cook that cannot lick his own fingers", 
"My conscience hath a thousand several tongues", 
"Strive mightily, but eat and drink as friends", 
"Mercy but murders, pardoning those that kill", 
"Nothing can seem foul to those that win", 
"French withered pears", 
"If the rascal hath not given me medicines to make me love him", 
"Ceremony was but devised at first to set a gloss on faint deeds", 
"To fear the worst oft cures the worse", 
"It is the bright day that brings forth the adder", 
"To business that we love we rise betime", 
"I tell you that which you yourselves do know", 
"I did send to you for certain sums of gold", 
"What angel wakes me from my flowery bed", 
"I will name you the degrees", 
"Thou art all ice", 
"Some men there are love not a gaping pig", 
"Lechery, sir, it provokes, and unprovokes", 
"They were red-hot with drinking", 
"Curse of marriage", 
"I would there were no age", 
"Things won are done", 
"Suit the action to the word", 
"Be great in act, as you have been in thought", 
"Men's evil manners live in brass", 
"Assume a virtue, if you have it not", 
"Men's vows are women's traitors", 
"Tis not enough to help the feeble up", 
"We go to gain a little patch of ground", 
"Sufferance is the badge of all our tribe", 
"Virtue that transgresses is but patched with sin", 
"Virtue itself turns vice", 
"The silence often of pure innocence persuades when speaking fails", 
"Where words are scarce, they are seldom spent in vain", 
"I am a very foolish fond old man", 
"I have no wife", 
"Men are April", 
"Do it with gentle means and easy tasks", 
"To be wise and love exceeds man's might", 
"Present fears are less than horrible imaginings", 
"A man loves the meat in his youth", 
"Do you set down your name in the scroll of youth", 
"The tender leaves of hopes", 
"I have immortal longings in me", 
"I have drunk, and seen the spider", 
"I must be cruel, only to be kind", 
"Win her with gifts, if she respect not words", 
"Tis a happy thing to be the father unto many sons", 
"Fathers that wear rags", 
"Now it is the time of night", 
"Now cracks a noble heart", 
"He wears his faith but as the fashion of his hat", 
"It is not politic in the commonwealth of nature to preserve virginity", 
"Blow, blow, thou winter wind", 
"I ne'er saw true beauty till this night", 
"One half of me is yours, the other half yours", 
"It is to be all made of fantasy", 
"Your grace is too costly to wear every day", 
"What's mine is yours and what is yours is mine", 
"One turf shall serve as pillow for us both", 
"It blows a man up like a bladder", 
"The first suit is hot and hasty", 
"Hourly joys be still upon you", 
"I have been to you a true and humble wife", 
"I will instruct my sorrows to be proud", 
"Moderate lamentation is the right of the dead", 
"Not a flower, not a flower sweet", 
"I cannot choose but weep", 
"To have seen much and to have nothing", 
"Good wine is a good familiar creature", 
"Very good orators, when they are out, they will spit", 
"Unbidden guests are often welcomest when they are gone", 
"Thou hast not loved", 
"You may think I love you not", 
"For never was a story of more woe Than this of Juliet and her Romeo", 
"Never doubt I love", 
"You cannot call it love", 
"Love is a smoke raised with the fume of sighs", 
"Your love deserves my thanks", 
"Where love is great, the littlest doubts are fear", 
"More fairer than fair", 
"I love you now,  but not, till now, so much", 
"Where there is true friendship", 
"Ask me no reason why I love you", 
"This love feel I, that feel no love in this", 
"By wailful sonnets, whose composed rhymes", 
"O, how I love thee! how I dote on thee!", 
"Give not this rotten orange to your friend", 
"I will never love that which my friend hates", 
"Songs and sonnets here", 
"Friendship is constant in all other things", 
"Your marriage comes by destiny", 
"Without the which we are pictures, or mere beasts", 
"We shall remain in friendship", 
"Think true love acted simple modesty", 
"With whom I am accused, I do confess", 
"Women are as roses", 
"You thief of love", 
"At christmas I no more desire a rose", 
"What stars do spangle heaven with such beauty", 
"Heaven knows how I love you", 
"Words, vows, gifts, tears, and love's full sacrifice", 
"Youth, beauty, wisdom, courage, all", 
"Either good or bad, but thinking makes it so", 
"I talk of dreams", 
"With three-fold love I wish you all these three", 
"Love, friendship, charity, are subjects all", 
"Your eyes are lode-stars", 
"What doth her beauty serve, but as a note", 
"The clown bore it, the fool sent it", 
"Revels his addiction leads him", 
"This bud of love, by summer's ripening breath", 
"Speak again, bright angel", 
"The sweet silent hours of marriage joys", 
"Lest your retirement do amaze your friends", 
"Here come two noble beasts in, a man and a lion", 
"Dash it like a christmas comedy", 
"Our revels now are ended", 
"My best beloved and approved friend", 
"The lunatic, the lover and the poet", 
"Earth-treading stars that make dark heaven light", 
"Tis the eye of childhood", 
"You would drink freely", 
"All the pictures fairest lined", 
"With any passion of inflaming love", 
"Under love's heavy burden do I sink", 
"Arise, fair sun, and kill the envious moon", 
"Your actions are my dreams", 
"The april 's in her eyes", 
"With lawyers in the vacation", 
"Whom I do love and will do till my death", 
"Unfold the passion of my love", 
"Take time to pause", 
"Fear no more the heat o' the sun", 
"With one soft kiss a thousand furlongs ere", 
"Seneca cannot be too heavy", 
"Which as they kiss consume: the sweetest honey", 
"Civil as an orange", 
"Speak the ceremonial rites of marriage", 
"His addiction was to courses vain", 
"Marriage, and god give thee joy", 
"With true-love showers", 
"The web of our life is of a mingled yarn", 
"My lips, two blushing pilgrims, ready stand", 
"My dreams presage some joyful news at hand", 
"Most radiant, exquisite and unmatchable beauty", 
"You have no cause to hold my friendship doubtful", 
"Fierce fiery warriors fought upon the clouds", 
"Full fathom five thy father lies", 
"Thy name and honourable family", 
"The be-all and the end-all", 
"Tell sad stories of the death of kings", 
"Childhood innocence", 
"A comfort of retirement lives in this", 
"What marriage is", 
"Your hopes and friends are infinite", 
"You to a love that your true faith doth merit", 
"You'll kiss me hard", 
"The floor of heaven", 
"Your sauciness will jest upon my love", 
"Will all great neptune's ocean wash this blood", 
"My life and education both do learn me", 
"If she unmask her beauty to the moon", 
"The shadow of a dream", 
"Most friendship is feigning, most loving mere folly", 
"If this were played upon a stage", 
"That often madness hits on", 
"Morning roses newly wash'd with dew", 
"There lives within the very flame of love", 
"The rest is silence", 
"So sweet a kiss the golden sun gives not", 
"I love you more than words can wield the matter", 
"May the winds blow till they have waken'd death", 
"Because I love you, I will let you know", 
"These flowers are like the pleasures of the world", 
"Liberty! Freedom! Tyranny is dead!", 
"Hath not in nature's mystery more science", 
"The sweetest sleep", 
"Some thousand verses of a faithful lover", 
"Your heart is burst, you have lost half your soul", 
"This whole earth may be bored", 
"Promise me friendship, but perform none", 
"I hate thee deadly", 
"There are princes and knights come", 
"Like to a lonely dragon", 
"To grace thy marriage-day", 
"Blow like sweet roses in this summer air", 
"That he may furnish and instruct great teachers", 
"To teach a teacher ill beseemeth me", 
"Sweet love! sweet lines! sweet life!", 
"This wide and universal theatre", 
"I had swinged him soundly", 
"A blinking idiot", 
"A king of infinite space", 
"A pound of flesh", 
"That way madness lies", 
"An improbable fiction", 
"The primrose path", 
"And thus I clothe my naked villany", 
"Antic disposition", 
"Breathe life into a stone", 
"Budge an inch", 
"Cakes and ale", 
"Chance may crown me", 
"Done to death by slanderous tongue", 
"Fair play", 
"Flaming youth", 
"For goodness' sake", 
"The crack of doom", 
"This thing of darkness", 
"Love all, trust a few, do wrong to none", 
"Hell is empty and all the devils are here", 
"He's mad that trusts in the tameness of a wolf", 
"I follow him to serve my turn upon him", 
"I go, and it is done,  the bell invites me", 
"I have a kind of alacrity in sinking", 
"I will buy with you, sell with you, talk with you", 
"Infirm of purpose", 
"It smells to heaven", 
"Knock, knock! Who's there?", 
"Laid on with a trowel", 
"More in sorrow than in anger", 
"Neither rhyme nor reason", 
"O villain, villain, smiling, damned villain!", 
"On the windy side", 
"Passing strange", 
"Put money in thy purse", 
"Sigh no more, ladies, sigh no more", 
"Some Cupid kills with arrows, some with traps", 
"Was ever woman in this humour woo'd?", 
"Vaulting ambition", 
"Swift as a shadow", 
"To be, or not to be"]